server:
  port: 8089

spring:
  application:
    name: cloud-feign-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/

# 全局配置
ribbon:
  # 连接超时时间
  ConnectTimeout: 500
  # 调用超时时间
  ReadTimeout: 2000

# 针对单个服务的 Ribbon 配置
cloud-eureka-client:
  ribbon:
    # 重试次数
    MaxAutoRetries: 2