server:
  port: 8077

spring:
  application:
    name: zuul-proxy

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/

zuul:
  routes: #给服务配置路由
    ser-client:
      path: /ser-client/**
    feign-service:
      path: /feign-service/**