spring:
  application:
    name: eur

#服务注册中心的端口
server:
  port: 8088

eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否将自己注册到 Eureka Server
    register-with-eureka: false
    #表示是否从 Eureka Server 获取注册信息
    fetch-registry: false
    #设置与 Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/